#!/usr/bin/env bash
# The whole of session C and session D in DRY mode, on the laptop, as a transcript
# (docs/gpu-experiments/03-acceleration/05-session-plan.md; the appendix 06-rehearsal.md is this output).
#
#   bash env/session/rehearse.sh [> docs/gpu-experiments/03-acceleration/06-rehearsal.md]
#
# Nothing is provisioned, copied or run: laptop.sh prints its TUI, ssh and rsync commands,
# vm.sh prints its stage commands and queue.sh prints one run_fleet.py line per queue row.
# The point is that every command of the plan exists, parses and is spelled the way the
# scripts spell it; a typo in a queue file or a stage name fails here, not on the VM.
# Round 2's rehearsal (sessions A and B) is docs/gpu-experiments/02-validation/05-rehearsal.md.
set -uo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT" || exit 1
export DRY=1 TUI="echo TUI" VM_IP_FILE=/tmp/rehearse.vm.ip LOGDIR=/tmp/rehearse.logs RECORD=/tmp/rehearse.record \
       FLEET_OUT=/tmp/rehearse.fleet_out SNAP=/model/snapshot REF_DIR=/tmp/rehearse.ref PY="$ROOT/.venv/bin/python"
rm -rf /tmp/rehearse.logs /tmp/rehearse.record /tmp/rehearse.fleet_out /tmp/rehearse.ref; mkdir -p /tmp/rehearse.ref
: > /tmp/rehearse.ref/ref_cache.safetensors
L="bash env/session/laptop.sh"; V="bash env/session/vm.sh"

h() { echo; echo "### $*"; echo; }
show() { echo '```'; "$@" 2>&1 | grep -v "^== \|^+ setsid" ; echo '```'; }
queue() { echo '```'; $V queue "$1" 2>&1 | grep "^+ .*run_fleet\|^+ .*measure\|^+ .*compare\|guard" | sed 's#--model-dir /model/snapshot##'; echo '```'; }

main() {
echo "# 06 - Rehearsal: every command of the two sessions, in DRY mode"
echo
echo "Generated by \`env/session/rehearse.sh\` on $(date -u +%Y-%m-%dT%H:%MZ). Each block is the"
echo "exact command the scripts run; \`+\` lines are what the VM or the laptop would execute."
echo "The laptop side is shown with the TUI replaced by \`echo TUI\` and the address 0.0.0.0;"
echo "the queue blocks show one \`run_fleet.py\` line per row (the model directory dropped)."

h "Session C, minute 0: the VM (grab.sh polls the list), the first push with the fork"
show $L provision
show env FULL=1 $L push

h "Session C, minute 2: the model, the build and the hardware record in parallel; the preflight"
show $L start download
show $L start setup
show $L start hw
echo "On the VM those become:"
show $V download
show $V setup
show $V preflight

h "Session C, minute 11: the day-1 checks and the reference"
show $V checks
show $V reference

h "Session C, minute 15: the suites, three builds"
show $V kernels
show $V kernels nt
show $V kernels mfma

h "Session C, minute 19: the standalone attention, merge and spin, three builds"
show $V ktime
show $V ktime nt
show $V ktime mfma

h "Session C, minute 23: G2, the baseline with the worker timing (queue-c2.txt)"
queue env/session/queue-c2.txt

h "Session C, minute 35: G3, the ladder (queue-c3.txt)"
queue env/session/queue-c3.txt

h "Session C, minute 55: the checkpoint, then G4, the knobs (queue-c4.txt)"
show $L pull
queue env/session/queue-c4.txt

h "Session C, minute 80: G5, the fusions (queue-c5.txt)"
queue env/session/queue-c5.txt

h "Session C, minute 105: G6, the probes and the streaming loads (queue-c6.txt)"
queue env/session/queue-c6.txt

h "Session C, minute 120 and the end: pull, balance, delete"
show $L pull
show $L report --balance
show $L delete --yes

h "Session D, minute 0 to 22: as session C to the suites (the MFMA build again), then G7 (queue-d7.txt)"
queue env/session/queue-d7.txt

h "Session D, minute 45: G8, the prefetch (queue-d8.txt), then the task-graph check on its first run"
queue env/session/queue-d8.txt
show $V tgcheck L2_it32_tile_fn1_fn2_fs_pf_wt

h "Session D, minute 100: G9, the final (queue-d9.txt)"
queue env/session/queue-d9.txt

echo
echo "Status files after the rehearsal (the rows every real run appends to):"
echo '```'; sed 's/^[0-9T:Z-]* //' /tmp/rehearse.logs/queue.status 2>/dev/null | sort -u | head -60; echo '```'
}

# the laptop's own path is not part of the record
main | sed "s#$ROOT#<repo>#g"
