#!/usr/bin/env bash
# The whole session (rows S0 to the end) in DRY mode, on the laptop, as a transcript
# (docs/gpu-experiments/04-kernels/07-session-plan.md; the appendix 08-rehearsal.md is this output).
#
#   bash env/session/rehearse.sh [> docs/gpu-experiments/04-kernels/08-rehearsal.md]
#
# Nothing is provisioned, copied or run: laptop.sh prints its TUI, ssh and rsync commands,
# vm.sh prints its stage commands and queue.sh prints one run_fleet.py line per queue row.
# The point is that every command of the plan exists, parses and is spelled the way the
# scripts spell it; a typo in a queue file or a stage name fails here, not on the VM.
# Round 3's rehearsal is docs/gpu-experiments/03-acceleration/06-rehearsal.md (its plan's
# rows, generated by the same script at that commit); round 2's is 02-validation/05-rehearsal.md.
set -uo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT" || exit 1
export DRY=1 TUI="echo TUI" VM_IP_FILE=/tmp/rehearse.vm.ip LOGDIR=/tmp/rehearse.logs RECORD=/tmp/rehearse.record \
       FLEET_OUT=/tmp/rehearse.fleet_out SNAP=/model/snapshot REF_DIR=/tmp/rehearse.ref PY="$ROOT/.venv/bin/python"
rm -rf /tmp/rehearse.logs /tmp/rehearse.record /tmp/rehearse.fleet_out /tmp/rehearse.ref; mkdir -p /tmp/rehearse.ref
: > /tmp/rehearse.ref/ref_cache.safetensors
L="bash env/session/laptop.sh"; V="bash env/session/vm.sh"

h() { echo; echo "### $*"; echo; }
show() { echo '```'; "$@" 2>&1 | grep -v "^== \|^+ setsid" ; echo '```'; }
queue() { echo '```'; $V queue "$1" 2>&1 | grep "^+ .*run_fleet\|^+ .*measure\|^+ .*compare\|guard" | sed 's#--model-dir /model/snapshot##'; echo '```'; }

main() {
echo "# 08 - Rehearsal: every command of the session, in DRY mode"
echo
echo "Generated by \`env/session/rehearse.sh\` on $(date -u +%Y-%m-%dT%H:%MZ). Each block is the"
echo "exact command the scripts run; \`+\` lines are what the VM or the laptop would execute."
echo "The laptop side is shown with the TUI replaced by \`echo TUI\` and the address 0.0.0.0;"
echo "the queue blocks show one \`run_fleet.py\` line per row (the model directory dropped)."
echo "The rows are those of \`07-session-plan.md\`."

h "Minute 0, S0: the VM (grab.sh polls the list), the first push with the fork"
show $L provision
show env FULL=1 $L push

h "Minute 2, S1: the model, the build and the hardware record in parallel; the preflight"
show $L start download
show $L start setup
show $L start hw
echo "On the VM those become:"
show $V download
show $V setup
show $V preflight

h "Minute 14, S2: the day-1 checks and the reference"
show $V checks
show $V reference

h "Minute 18, S3: the suites, the plain and the streaming build (the gang GEMV rows through the _xcd builds)"
show $V kernels
show $V kernels nt

h "Minute 30, S4: the standalone times, the batch constant and the lane map (G0, H0)"
show $V ktime nt
show $V ktime nt_b4
show $V ktime nt_b16
show $V ktime nt_strided
show $V ktime

h "Minute 40, S5: G1 and G2, the GEMV linears against the CK build, the grid sweep (queue-f2.txt)"
queue env/session/queue-f2.txt

h "Minute 54, S6: G3 and G4, the w2 GEMV form and w13 in one round (queue-f3.txt)"
queue env/session/queue-f3.txt

h "Minute 62, S7: H2 and H4, the router in four tasks and the merge as regular tasks (queue-g1.txt)"
queue env/session/queue-g1.txt

h "Minute 74, S8: H5, the merge with o_proj folded in (queue-g2.txt), then the task-graph check on its first run"
queue env/session/queue-g2.txt
show $V tgcheck L2_it1_tile_at_fn1_fn2_fs_nt_nts_mfma_gv_w13_rt_mo

h "Minute 78, S9: the checkpoint, then G5 and G6, the stream probe and the head (queue-f4.txt)"
show $L pull
queue env/session/queue-f4.txt

h "Minute 88, S10: a lever out of the finals (the mid-session edit), then the finals (queue-f5.txt)"
echo '```'; python3 env/session/queue_flag.py env/session/queue-f5.txt --remove --merge-oproj | grep -v "^#" | head -1; python3 env/session/queue_flag.py env/session/queue-f5.txt --head-grid 320 | grep -v "^#" | head -1; echo '```'
queue env/session/queue-f5.txt

h "Minute 96, S11: the checkpoint and the balance"
show $L pull
show $L report --balance

h "Minute 100, S12: G9, the knobs (queue-f6.txt), if time"
queue env/session/queue-f6.txt

h "Minute 120, S13: G8, the bit-diff of the CK build's and the GEMV build's step-0 runs, if time"
show bash env/session/queue.sh bitdiff L2_it1_tile_at_fn1_fn2_fs_nt_nts_mfma_rf_MPK_W2_CK_TILE L2_it1_tile_at_fn1_fn2_fs_nt_nts_mfma_rf_MPK_W2_CK_TILE_gv

h "Minute 125, S14: a knob into the finals, then the finals again"
echo '```'; python3 env/session/queue_flag.py env/session/queue-f5.txt --runtime-flags=-DMPK_POLL_SLEEP=8 | grep -v "^#" | head -1; echo '```'

h "The end: pull, balance, then the deletion after the user's yes"
show $L pull
show $L report --balance
show $L delete --yes

echo
echo "Status files after the rehearsal (the rows every real run appends to):"
echo '```'; sed 's/^[0-9T:Z-]* //' /tmp/rehearse.logs/queue.status 2>/dev/null | sort -u | head -80; echo '```'
}

# the laptop's own path is not part of the record
main | sed "s#$ROOT#<repo>#g"
